server:
  port: 8081

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce_catalog
    username: deniz
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false # Performans uyarısını kapatır (Best Practice)
    hibernate:
      # İLK ÇALIŞTIRMADA 'create' KALSIN, tablolar oluşunca 'update' YAPARSIN.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true