services:
  postgres:
    image: 'postgres:latest'
    container_name: 'merchant-db'
    environment:
      - 'POSTGRES_DB=ecommerce_merchant'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=deniz'
    ports:
      - '5434:5432'